hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/BST.o -c ./src/BST.cpp
	g++ -I ./include/ -o ./lib/Dosya.o -c ./src/Dosya.cpp
	g++ -I ./include/ -o ./lib/Test.o -c ./src/Test.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/BST.o ./lib/Dosya.o ./lib/Test.o
calistir:
	./bin/Test